export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { stripe } from "@/lib/stripe";
import { createSupabaseServiceRole } from "@/lib/supabase/server";
import { sendEmail } from "@/lib/email";

export async function POST(req: Request) {
  const body = await req.text();
  const headersList = await headers();
  const signature = headersList.get("stripe-signature");

  if (!signature) {
    return NextResponse.json(
      { error: "No signature found" },
      { status: 400 }
    );
  }

  if (!process.env.STRIPE_WEBHOOK_SECRET) {
    console.error("STRIPE_WEBHOOK_SECRET is not set");
    return NextResponse.json(
      { error: "Webhook secret not configured" },
      { status: 500 }
    );
  }

  let event;

  try {
    event = stripe.webhooks.constructEvent(
      body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET
    );
  } catch (err: any) {
    console.error("Webhook signature verification failed:", err.message);
    return NextResponse.json(
      { error: `Webhook Error: ${err.message}` },
      { status: 400 }
    );
  }

  // Handle the event
  switch (event.type) {
    case "payment_intent.succeeded":
      const paymentIntent = event.data.object;
      await handlePaymentIntentSucceeded(paymentIntent);
      break;

    case "payment_intent.payment_failed":
      const failedPayment = event.data.object;
      await handlePaymentFailed(failedPayment);
      break;

    case "payment_intent.canceled":
      const canceledPayment = event.data.object;
      console.log("PaymentIntent canceled:", canceledPayment.id);
      break;

    default:
      console.log(`Unhandled event type: ${event.type}`);
  }

  return NextResponse.json({ received: true });
}

async function handlePaymentIntentSucceeded(paymentIntent: any) {
  const supabase = createSupabaseServiceRole();

  if (!supabase) {
    console.error("Service role client not available");
    return;
  }

  try {
    const metadata = paymentIntent.metadata;
    const userId = metadata.user_id;

    if (!userId) {
      console.error("No user_id in payment intent metadata");
      return;
    }

    // Parse shipping address from metadata
    const shippingAddress = JSON.parse(metadata.shipping_address || "{}");

    // Get cart items for order items creation
    const { data: cartItems, error: cartError } = await supabase
      .from("cart_items")
      .select(
        `
        id,
        product_id,
        quantity,
        price_at_add,
        products (
          name,
          sku,
          primary_image_url
        )
      `
      )
      .eq("user_id", userId);

    if (cartError || !cartItems || cartItems.length === 0) {
      console.error("Error fetching cart items:", cartError);
      return;
    }

    // Create the order (order_number will be auto-generated by database trigger)
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        user_id: userId,
        customer_email: metadata.customer_email,
        customer_name: metadata.customer_name,
        customer_phone: metadata.customer_phone || null,
        shipping_address_line1: shippingAddress.line1,
        shipping_address_line2: shippingAddress.line2 || null,
        shipping_city: shippingAddress.city,
        shipping_state: shippingAddress.state,
        shipping_zip: shippingAddress.zip,
        subtotal: parseFloat(metadata.subtotal),
        tax_amount: parseFloat(metadata.tax),
        shipping_cost: parseFloat(metadata.shipping),
        total_amount: parseFloat(metadata.total),
        payment_status: "paid",
        order_status: "processing",
        payment_intent_id: paymentIntent.id,
        payment_method: "card",
        customer_notes: metadata.customer_notes || null,
        paid_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (orderError || !order) {
      console.error("Error creating order:", orderError);
      return;
    }

    // Create order items
    const orderItems = cartItems.map((item: any) => ({
      order_id: order.id,
      product_id: item.product_id,
      quantity: item.quantity,
      unit_price: item.price_at_add,
      total_price: item.price_at_add * item.quantity,
      product_name: item.products?.name || "Unknown Product",
      product_sku: item.products?.sku || null,
      product_image_url: item.products?.primary_image_url || null,
    }));

    const { error: orderItemsError } = await supabase
      .from("order_items")
      .insert(orderItems);

    if (orderItemsError) {
      console.error("Error creating order items:", orderItemsError);
      return;
    }

    // Update product stock quantities
    for (const item of cartItems) {
      // Get current stock
      const { data: product } = await supabase
        .from("products")
        .select("stock_quantity")
        .eq("id", item.product_id)
        .single();

      if (product) {
        const newStock = product.stock_quantity - item.quantity;
        const { error: stockError } = await supabase
          .from("products")
          .update({ stock_quantity: newStock })
          .eq("id", item.product_id);

        if (stockError) {
          console.error("Error updating stock:", stockError);
        }
      }
    }

    // Clear user's cart
    const { error: clearCartError } = await supabase
      .from("cart_items")
      .delete()
      .eq("user_id", userId);

    if (clearCartError) {
      console.error("Error clearing cart:", clearCartError);
    }

    console.log(
      `Order ${order.id} created successfully for PaymentIntent ${paymentIntent.id}`
    );

    // Send order confirmation email
    try {
      const orderItemsHtml = cartItems
        .map(
          (item: any) => `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">
            <strong>${item.products?.name || "Unknown Product"}</strong><br/>
            <span style="color: #6b7280; font-size: 14px;">Quantity: ${item.quantity}</span>
          </td>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">
            $${(item.price_at_add * item.quantity).toFixed(2)}
          </td>
        </tr>
      `
        )
        .join("");

      const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Order Confirmation</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f9fafb;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">
    <!-- Header -->
    <div style="background-color: #2563eb; padding: 40px 20px; text-align: center;">
      <h1 style="color: #ffffff; margin: 0; font-size: 28px;">Order Confirmed!</h1>
      <p style="color: #e0e7ff; margin: 10px 0 0 0;">Thank you for your purchase</p>
    </div>

    <!-- Content -->
    <div style="padding: 40px 20px;">
      <!-- Order Info -->
      <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
        <p style="margin: 0 0 10px 0; color: #374151;">
          <strong>Order Number:</strong> ${order.order_number}
        </p>
        <p style="margin: 0 0 10px 0; color: #374151;">
          <strong>Order Date:</strong> ${new Date(order.created_at).toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </p>
        <p style="margin: 0; color: #374151;">
          <strong>Payment Status:</strong> <span style="color: #059669;">Paid</span>
        </p>
      </div>

      <!-- Greeting -->
      <p style="color: #374151; font-size: 16px; line-height: 1.6;">
        Hi <strong>${metadata.customer_name}</strong>,
      </p>
      <p style="color: #374151; font-size: 16px; line-height: 1.6;">
        We've received your order and it's being processed. You'll receive a shipping confirmation email with tracking information once your order ships.
      </p>

      <!-- Order Items -->
      <h2 style="color: #111827; font-size: 20px; margin: 30px 0 15px 0;">Order Items</h2>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead>
          <tr style="background-color: #f9fafb;">
            <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Item</th>
            <th style="padding: 12px; text-align: right; border-bottom: 2px solid #e5e7eb;">Price</th>
          </tr>
        </thead>
        <tbody>
          ${orderItemsHtml}
        </tbody>
      </table>

      <!-- Order Summary -->
      <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
        <table style="width: 100%;">
          <tr>
            <td style="padding: 8px 0; color: #6b7280;">Subtotal</td>
            <td style="padding: 8px 0; text-align: right; color: #374151;">$${metadata.subtotal}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #6b7280;">Tax</td>
            <td style="padding: 8px 0; text-align: right; color: #374151;">$${metadata.tax}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #6b7280;">Shipping</td>
            <td style="padding: 8px 0; text-align: right; color: #374151;">$${metadata.shipping}</td>
          </tr>
          <tr style="border-top: 2px solid #e5e7eb;">
            <td style="padding: 12px 0 0 0;"><strong style="color: #111827; font-size: 18px;">Total</strong></td>
            <td style="padding: 12px 0 0 0; text-align: right;"><strong style="color: #111827; font-size: 18px;">$${metadata.total}</strong></td>
          </tr>
        </table>
      </div>

      <!-- Shipping Address -->
      <h2 style="color: #111827; font-size: 20px; margin: 30px 0 15px 0;">Shipping Address</h2>
      <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
        <p style="margin: 0; color: #374151; line-height: 1.6;">
          ${shippingAddress.line1}<br/>
          ${shippingAddress.line2 ? shippingAddress.line2 + "<br/>" : ""}
          ${shippingAddress.city}, ${shippingAddress.state} ${shippingAddress.zip}
        </p>
      </div>

      <!-- What's Next -->
      <div style="background-color: #eff6ff; border-left: 4px solid #2563eb; padding: 20px; margin-bottom: 30px;">
        <h3 style="color: #1e40af; margin: 0 0 10px 0; font-size: 18px;">What Happens Next?</h3>
        <ol style="margin: 0; padding-left: 20px; color: #374151; line-height: 1.8;">
          <li>We're preparing your order for shipment</li>
          <li>You'll receive a shipping confirmation with tracking number</li>
          <li>Your order will arrive within 5-7 business days</li>
        </ol>
      </div>

      <!-- Support -->
      <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin: 30px 0 0 0; text-align: center;">
        Questions about your order? Contact us at
        <a href="mailto:support@medconnect.com" style="color: #2563eb; text-decoration: none;">support@medconnect.com</a>
      </p>
    </div>

    <!-- Footer -->
    <div style="background-color: #f9fafb; padding: 30px 20px; text-align: center; border-top: 1px solid #e5e7eb;">
      <p style="color: #6b7280; font-size: 14px; margin: 0 0 10px 0;">
        Thank you for shopping with MedConnect
      </p>
      <p style="color: #9ca3af; font-size: 12px; margin: 0;">
        &copy; ${new Date().getFullYear()} MedConnect. All rights reserved.
      </p>
    </div>
  </div>
</body>
</html>
      `;

      await sendEmail({
        to: metadata.customer_email,
        subject: `Order Confirmation - ${order.order_number}`,
        html: emailHtml,
      });

      console.log(`Order confirmation email sent to ${metadata.customer_email}`);
    } catch (emailError) {
      console.error("Error sending order confirmation email:", emailError);
      // Don't fail the webhook if email fails - order is still created
    }
  } catch (error) {
    console.error("Error in handlePaymentIntentSucceeded:", error);
  }
}

async function handlePaymentFailed(paymentIntent: any) {
  console.log(`Payment failed for PaymentIntent ${paymentIntent.id}`);

  // If an order was already created, mark it as failed
  const supabase = createSupabaseServiceRole();

  if (!supabase) {
    console.error("Service role client not available");
    return;
  }

  const { data: order } = await supabase
    .from("orders")
    .select("id")
    .eq("payment_intent_id", paymentIntent.id)
    .single();

  if (order) {
    await supabase
      .from("orders")
      .update({
        payment_status: "failed",
        order_status: "cancelled",
      })
      .eq("id", order.id);

    console.log(`Order ${order.id} marked as failed`);
  }
}
